### ISSUE TITLE
Get type error when using `scalar` in `asNexusMethod` after update to `1.0.3`

### ISSUE THREAD

**Issue by vimutti77** [graphql-nexus/nexus-prisma#383] opened 2023-01-17 02:16 UTC
### Instructions
1. Update `nexus-prisma` from `0.35.0` to `1.0.3`
2. Using this code
```ts
import { asNexusMethod } from 'nexus'
import { DateTime } from 'nexus-prisma/scalars'

export const DateTimeScalar = asNexusMethod(DateTime, 'dateTime', 'Date | string')
```
3. Type error
```
Argument of type 'AllNexusOutputTypeDefs' is not assignable to parameter of type 'GraphQLNamedType'.
  Type 'NexusListDef<any>' is not assignable to type 'GraphQLNamedType'.ts(2345)
```

#### nexus-prisma v0.35.0
Type of DateTime is `GraphQLScalarType`
![image](https://user-images.githubusercontent.com/27840664/212794386-eb5888e0-5d40-4550-8b19-512f9eb2974e.png)

#### nexus-prisma v1.0.3
Type of DateTime is `AllNexusOutputTypeDefs`
![image](https://user-images.githubusercontent.com/27840664/212794652-d0686d78-0bcc-40ab-8bfd-20d87176acf1.png)

**Comment by rostislav-simonik** [comment] 2023-01-30 19:32
@vimutti77 it's probably not a bug, but breaking change introduced by nexus@1.2.0 -> nexus @1.3.0 see https://github.com/graphql-nexus/nexus/pull/983, `asNexusMethod` doesn't return GraphQLNamedType as return type anymore, but internal AllNexusOutputTypeDefs or AllNexusInputTypeDefs. `asNexusMethod` could also accept AllNexusOutputTypeDefs or AllNexusInputTypeDefs as input.

But if you need to specify sourceType value, just extract following [code](https://github.com/graphql-nexus/nexus-prisma/blob/main/src/scalars/DateTime.ts#L34) into your code base, or just cast the type to GraphQLNamedType,

**Comment by rostislav-simonik** [comment] 2023-02-07 17:17
@vimutti77 closing ticket, if anything, feel free to reopen.

**Closed as completed by rostislav-simonik** 2023-02-07 17:17 UTC
